### ISSUE TITLE
Issue when logging in

### ISSUE THREAD

**Issue by PatrickOslo** [Shade-/MyFacebook-Connect#45] opened 2015-04-19 10:18 UTC
Image of the error messge: http://puu.sh/hjc0T/d674b3c065.png

Following images are from the facebook settings:
http://puu.sh/hjc7C/8273a0ca60.png
http://puu.sh/hjc8x/cc55e2a5db.png
http://puu.sh/hjc9a/c81c4cc3c8.png
http://puu.sh/hjc9L/3939d42239.png

Thanks for the support.

**Comment by NewEraCracker** [comment] 2015-04-19 21:51
Problems with Facebook API ?

Readme states this info:

**MyFacebook Connect is licensed under MIT and it is based upon Facebook SDK version 3.2.3, which is known to expire in April, 2015.**

**Comment by NewEraCracker** [comment] 2015-04-19 21:54
Or maybe this is just like issue #44 where the author states: "This is usually caused by your server which does not have port 443 opened (you need to open it if this is the case)."

**Comment by PatrickOslo** [comment] 2015-04-19 22:02
Checked the port and hostgator has the ssl port open by default on their packages. Talked with their support. Thanks for the message tho.

**Comment by Shade-** [comment] 2015-04-28 11:10
Could you try the latest update I've submitted? Version 2.2 includes a handy port check fired upon installation and an update to the latest Facebook SDK.

**Comment by Shade-** [comment] 2015-09-20 10:48
No answers so I close this. Feel free to reopen if you encounter the same problem again with the latest version.

**Closed by Shade-** 2015-09-20 10:48 UTC
